remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-multiple-languages-plugin

title: [Dan's CV] 
description: [A short story in bullet points]

languages:  
- en  
- de
default_lang: en

defaults:
  - scope:
      path: ""
    values:
      layout: default
      lang: en
  - scope:
      path: "en"
    values:
      lang: en
  - scope:
      path: "de"
    values:
      lang: de


baseurl: "/persona"
url: "https://danm3rcurius.github.io"